# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lab1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlab1.proto\x12\x07lab1prc\")\n\x06Sample\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\r\n\x05label\x18\x02 \x01(\x05\"+\n\x07\x44\x61taset\x12 \n\x07samples\x18\x01 \x03(\x0b\x32\x0f.lab1prc.Sample\"/\n\nFitRequest\x12!\n\x07\x64\x61taset\x18\x01 \x01(\x0b\x32\x10.lab1prc.Dataset\"\x1f\n\x0b\x46itResponse\x12\x10\n\x08\x61\x63\x63uracy\x18\x01 \x01(\x02\"\"\n\x0ePredictRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\"*\n\x0fPredictResponse\x12\x17\n\x0fpredicted_label\x18\x01 \x01(\x05\x32w\n\x02ML\x12\x34\n\x05train\x12\x13.lab1prc.FitRequest\x1a\x14.lab1prc.FitResponse\"\x00\x12;\n\x04\x65val\x12\x17.lab1prc.PredictRequest\x1a\x18.lab1prc.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLE']._serialized_start=23
  _globals['_SAMPLE']._serialized_end=64
  _globals['_DATASET']._serialized_start=66
  _globals['_DATASET']._serialized_end=109
  _globals['_FITREQUEST']._serialized_start=111
  _globals['_FITREQUEST']._serialized_end=158
  _globals['_FITRESPONSE']._serialized_start=160
  _globals['_FITRESPONSE']._serialized_end=191
  _globals['_PREDICTREQUEST']._serialized_start=193
  _globals['_PREDICTREQUEST']._serialized_end=227
  _globals['_PREDICTRESPONSE']._serialized_start=229
  _globals['_PREDICTRESPONSE']._serialized_end=271
  _globals['_ML']._serialized_start=273
  _globals['_ML']._serialized_end=392
# @@protoc_insertion_point(module_scope)
